export const GET_MARVELS_REQUEST = 'GET_MARVELS_REQUEST';
export const GET_MARVELS_SUCCESS = 'GET_MARVELS_SUCCESS';
export const GET_MARVELS_FAILURE = 'GET_MARVELS_FAILURE';

export const SEND_FEEDBACK = 'SEND_FEEDBACK';
export const SET_FEEDBACK_INACTIVE = 'SET_FEEDBACK_INACTIVE';
